version: "3"

services:
  mysql:
    container_name: database
    image: mysql:5.7
    volumes:
      - game-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: jogos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3388:3306"

  app:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/app
    depends_on:
      - "mysql"

volumes:
  game-mysql-data:
