version: "3"

services:
  mysql:
    container_name: database
    image: mysql:5.7
    volumes:
      - game-mysql-data:/var/lib/mysql
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3388:3306"


  app:
    build: .
    command: npm start
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/app

  

volumes:
  game-mysql-data:
